### ISSUE TITLE
Underscores description should be updated

### ISSUE THREAD

**Issue by Latimew333** [placeAtlas/atlas-2022#1462]
Location is 480,734. The current description deadnames and misgenders underscores, it should be changed to read "underscores, real name April Harper Grey, is an American EDM/hyperpop music producer, born in California and based in New York. She is also a member of the group Six Impala."

**Comment by Codixer** [comment]
You're able to edit it on https://2023.place-atlas.stefanocoding.me/ if you want, most/almost all entries go through Reddit/GitHub for anyone to see.

**Comment by Latimew333** [comment]
hey this was closed awhile ago but it still hasn't moved from cleanup to the main branch, how long should it take for that to happen?

**Comment by Latimew333** [comment]
I can't even see the patch in cleanup anymore so I'm not sure if the change wasn't lost or something

**Comment by Latimew333** [comment]
yeah looking at atlas.json in the cleanup branch it still has the old description so it looks like it was just never actually applied or something? Can this be reopened until it's actually fixed?

**Comment by Hans5958** [comment]
That's weird. The PR should have been merged and the changes have been incorporated. I have recreated the patch on #1485 but I'll have take a closer look on it.

**Comment by Hans5958** [comment]
I found the culprit. #1479 removed the patch before it got implemented on the main data.
